apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres-auth-svc:5432/postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"