apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-auth-pv
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/postgres-auth-pv